# Generated by Django 4.2.3 on 2023-07-17 15:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Товари')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Ціна')),
            ],
        ),
    ]
