# Generated by Django 4.2.3 on 2023-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='active',
            field=models.FloatField(default=False, help_text='Показувати або не показувати товар', verbose_name='Active'),
        ),
    ]
