# Generated by Django 4.2.3 on 2023-07-19 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Предмети для власного декору')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Опис')),
                ('price', models.FloatField(verbose_name='Ціна')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Товари'),
        ),
    ]
