# Generated by Django 4.2.3 on 2023-07-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_itemsdecor_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdecor',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Предмети для власного декору'),
        ),
    ]
