# Generated by Django 4.2.3 on 2023-07-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_itemsdecor_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsdecor',
            name='active',
        ),
        migrations.RemoveField(
            model_name='itemsdecor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemsdecor',
            name='price',
        ),
    ]
