# Generated by Django 4.2.3 on 2023-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_itemsdecor_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsdecor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Предмети для власного декору'),
        ),
    ]
