# Generated by Django 4.2.3 on 2023-07-19 18:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_itemsdecor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsdecor',
            name='description',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
